### ISSUE TITLE
question regarding available data

### ISSUE THREAD

**Issue by radekosmulski** [woestreich/blue-whale-migration#1]
Hi Will!

I have been looking through the repository - thank you for making the code public!

Could I please ask you a question regarding the information from the README below?
![image](https://user-images.githubusercontent.com/2444926/114851534-39a1b200-9de2-11eb-82c1-f44075c40e6c.png)

Do any of the `.mat` files contain the 30 minute audio? I tried searching for it but couldn't find it.

Thank you!
Radek

**Comment by woestreich** [comment]
Hi Radek,

Thanks for pointing out this error. This was an error in the README description of the "acoustic_data" directory, which has now been corrected. The file that the bullet point you have highlighted refers to is "acoustic_data/bluewhalesong_ltsa_20161101h1.mat". It is actually a 30-minute data chunk, and it is an LTSA of the MARS data (most useful for calculating song call index).
